[SINT-1180] Index Allowlist
DataDog/yorkshire pull request #7
Opened 2023-03-30 09:50 UTC by cedricvanrompay-datadog

2023-04-06 10:47 UTC, fridex requested changes

2023-04-06 10:47 UTC, fridex commented on yorkshire/cli.py
> +    '--allowed-index',
```suggestion
    '--allowed-index-url',
```

2023-04-06 10:47 UTC, fridex commented on yorkshire/cli.py
> +def cli_detect(ctx: click.core.Context, path: str, allowed_indexes: Iterable[str]) -> None:
Name of the argument needs to match the CLI option:

```suggestion
def cli_detect(ctx: click.core.Context, path: str, allowed_index_url: Tuple[str]) -> None:
```

Also, click passes a `Tuple` in this case.

2023-04-06 10:47 UTC, fridex commented on yorkshire/cli.py
> +    okay = all([i[1] for i in yorkshire.detect(path, allowed_indexes)])
```suggestion
    okay = all([i[1] for i in yorkshire.detect(path, allowed_index_url)])
```

2023-04-06 10:47 UTC, fridex commented on yorkshire/cli.py
> +from typing import Iterable
```suggestion
from typing import Tuple
```

2023-04-06 10:47 UTC, fridex commented on tests/test_detect_file.py
> +    def test_fail(self, filepath: str, index_allowlist: bool) -> None:
Could `index_allowlist` be part of the `pytest.mark.parametrize`? Other tests use it, and it looks kind of weird to combine both. Also, `ALLOWED_INDEXES` could become part of the `pytest.mark.parametrize` as well.

2023-04-06 10:47 UTC, fridex commented on yorkshire/_lib.py
> +    ]
Could this be rewritten to a more readable form (also below)?

2023-04-12 07:54 UTC, cedricvanrompay-datadog commented
@fridex should be all done

2023-05-16 09:49 UTC, fridex approved these changes

2023-05-16 09:49 UTC, merged